const platos = [
    {
        id: 1,
        nombre: "Huevos con tostadas",
        precio: 15000,
        imagen: "./assets/break1.jpg",
        descripcion: "Huevos con tostadas, mantequilla y arepa con queso.",
        categoria: "desayuno",
    },
    {
        id: 2,
        nombre: "Panqueques",
        precio: 15000,
        imagen: "./assets/break2.jpg",
        descripcion: "Panqueques con fresas y mermelada de mora.",
        categoria: "desayuno",
    },
    {
        id: 3,
        nombre: "Panqueques",
        precio: 17000,
        imagen: "./assets/break3.jpg",
        descripcion:
            "Panqueques con dulce de leche, fresas, arandanos y azucar glass.",
        categoria: "desayuno",
    },
    {
        id: 4,
        nombre: "Sánduche",
        precio: 10000,
        imagen: "./assets/break4.jpg",
        descripcion: "Sánduche de jamón con lechuga, cebolla y salsa especial.",
        categoria: "desayuno",
    },
    {
        id: 5,
        nombre: "Huevos cocidos",
        precio: 16000,
        imagen: "./assets/lunch.jpg",
        descripcion: "Huevos cocidos con tostadas a las finas hierbas.",
        categoria: "almuerzo",
    },
    {
        id: 6,
        nombre: "Pastas a la margarita",
        precio: 20000,
        imagen: "./assets/lunch2.jpg",
        descripcion: "Pastas con tomate, queso y albahaca.",
        categoria: "almuerzo",
    },
    {
        id: 7,
        nombre: "Ensalada",
        precio: 22000,
        imagen: "./assets/lunch3.jpg",
        descripcion: "Mix de verduras y frutas con salsa especial.",
        categoria: "almuerzo",
    },
    {
        id: 8,
        nombre: "Arroz con sopa",
        precio: 17000,
        imagen: "./assets/dinner.jpg",
        descripcion: "Sopa de verduras con arroz.",
        categoria: "cena",
    },
    {
        id: 9,
        nombre: "Carne de res",
        precio: 35000,
        imagen: "./assets/dinner2.jpg",
        descripcion: "Lomo de res con verduras y salsa especial.",
        categoria: "cena",
    },
    {
        id: 10,
        nombre: "Café",
        precio: 8000,
        imagen: "./assets/shake1.jpg",
        descripcion: "Café con crema de leche y pan.",
        categoria: "batido",
    },
    {
        id: 11,
        nombre: "Batido de fresa",
        precio: 11000,
        imagen: "./assets/shake2.jpg",
        descripcion: "Batido de fresa con leche.",
        categoria: "batido",
    },
    {
        id: 12,
        nombre: "batido triple",
        precio: 14500,
        imagen: "./assets/shake3.jpg",
        descripcion: "Huevos con tostadas, mantequilla y arepa con queso.",
        categoria: "batido",
    },
];

export { platos };
